### ISSUE TITLE
Consider integrating CI services

### ISSUE THREAD

**Issue by peter279k** [Lawondyss/Config#1]
As title, I think it's nice to have the CI service to integrate this PHP package :).

And I also recommend using the GitHub Action Workflow because it''s supported by GitHub directly.

And we don't have to connect third-party CI service to resolve this issue.

Once this issue is accepted by @Lawondyss, I would be happy to work on this :smile:.

**Comment by Lawondyss** [comment]
OK, i like that idea. So, show what you can do 😃
