### ISSUE TITLE
Consider integrating coding style

### ISSUE THREAD

**Issue by peter279k** [Lawondyss/Config#2]
As title, I think it's nice to let this PHP package have a good coding style.

I also recommend we can use `PHP_CodeSniffer` or `PHP-CS-Fixer` to follow `PSR-2` or `PSR-12` coding style and resolve this issue.

Once it's accepted by repository owner, I will be happy to work on this.

**Comment by Lawondyss** [comment]
I have own coding style, but if you think, it is good idea... Go on 👍
